// build info - autogenerated do not manually edit
//
//
#ifndef BUILD_INFO_H_
#define BUILD_INFO_H_

//
// Build number
//

// Provide an incremental integer build number//
#define __BI__BUILD_TYPE_STR "DEV"
#define __BI__BUILD_NUMBER 0
#define __BI__BUILD_NUMBER_STR "DEV-0"

//
// Build date & time stamp for 2020:02:26 22:52:45
//

// Provide an integer representation of the time in human-readable form
#define __BI__TIMESTAMP_INT 220000

// Provide a 3 8-bit representation of the time in human-readable form
#define __BI__TIMESTAMP_INT8_HR 22
#define __BI__TIMESTAMP_INT8_MI 00
#define __BI__TIMESTAMP_INT8_SE 00

// Provide a 6 byte string representation of the time
#define __BI__TIMESTAMP_STR "220000"


// Provide an integer representation of the date in human-readable form
#define __BI__DATESTAMP_INT 201227

// Provide a 3 8-bit representation of the date in human-readable form
#define __BI__DATESTAMP_INT8_YR 20
#define __BI__DATESTAMP_INT8_MO 12
#define __BI__DATESTAMP_INT8_DA 27

// Provide a 6 byte string representation of the date
#define __BI__DATESTAMP_STR "201227"

#define __BI__DATEANDTIMESTAMP_STR "201227-220000"
#endif /* BUILD_INFO_H_ */

